services:
  - type: web
    name: eoir-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind=0.0.0.0:10000
